package com.application;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
/*import java.text.SimpleDateFormat;
import java.util.Date;
import org.springframework.beans.factory.annotation.Autowired;
import com.application.model.AccountHolder;
import com.application.model.Policy;
import com.application.repository.PolicyRepository;*/
/**
 * Autogenerated file - Was modified to implement CommandLineRunner to check addition of record into MongoDB (commented now)
 * @author NS
 *
 */
@SpringBootApplication
public class Insurance1Application implements CommandLineRunner {
		
	/*@Autowired
	private PolicyRepository policyRepository;*/
		
	public static void main(String[] args) {
		SpringApplication.run(Insurance1Application.class, args);
	}
	@Override
	public void run(String... args) throws Exception {
		/*AccountHolder holder 
			= new AccountHolder("3", "Nilima","Ajay", 
					new SimpleDateFormat("dd/MM/yy").parse("22/02/1951"), "nie@ddmc.com");
			
		Policy policy = new Policy("HLT1111", 10000, holder);
		policyRepository.save(policy);*/
	}
	
}
