package com.application;
import com.application.Insurance1Application;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

/**
 * Autogenerated test class - not being used - can be ignored
 *
 */
@RunWith(SpringRunner.class)
@SpringBootTest
public class Insurance1ApplicationTests {

	@Test
	public void contextLoads() {
	}

}
